language: cpp
dist: bionic

matrix:
  include:
    - os: linux
      dist: bionic
      sudo: required
      install: ".travis/linux/deps.sh"
      script: ".travis/linux/build.sh"

    - os: osx
      sudo: required # see the build script...
      osx_image: xcode10.1 # =10.13/high sierra
      install: ".travis/macos/deps.sh"
      script: ".travis/macos/build.sh"
      cache:
        directories:
          - $HOME/Library/Caches/Homebrew
      before_cache:
        - brew cleanup

    - os: windows
      before_install: ".travis/win32/preinstall.sh"
      install:
        - cmd /c\ "C:\\tools\\msys64\\usr\\bin\\bash.exe -lc 'sh .travis/win32/deps.sh'"
        - taskkill //IM gpg-agent.exe //F //FI "STATUS eq RUNNING" # https://travis-ci.community/t/4967
      script:
        - cmd /c\ "C:\\tools\\msys64\\usr\\bin\\bash.exe -lc 'sh .travis/win32/build.sh'"
      #before_cache:
        #- |-
          #$msys2 pacman --sync --clean --noconfirm
      cache:
        directories:
          - $HOME/AppData/Local/Temp/chocolatey
          - /C/tools/msys64

deploy:
  provider: releases
  api_key:
    secure: "XjHXrtaq9VSLL/zA1BKnrFNHrDuz4WUtn9JJs0EnngUt6zjw1q4Z2suVIw4iXWXkblWLIuA+HHXbM0RsiKHvc8FLFuZWpVkV/hz/AXLEZ40Yn+hW3b3z1zaNXFotXiKC+gmJcOgVo3/BQst1dG3gmUv2IM3JhYa4I3jzR9q5AqSqWbH8B1UdpB46St7D27kGdqt6tJAHZtKmyYRP7GfgeIVrCoOrhvgpFgzrj4p2yKy5voQWulXpyRyooaGOfXMzkcFzsiZLbJhLm3BaiFUOyRINufijjeDlyX5Df05a5x6uVxTZfjLFOyfzxTPpI/fMqNoYlRqvheoMVjGAu3s+e3KvllMM4hxD2M0J6WFV6beyzJqIwgR7Z3wgac5E2RJfQYo3S4V2SlKUAxqx4KXdQAiJ3VqdlE8V6p4eyoPIQFrJpsUfUye4d5rKj/U3SOD9OP9PDqNUEzzdwxYh4V0qexHJnegw4BOHIqIS+yr/fv2thJ27/mghG6a4rqxwbhANL7B3ZUVkFh6X+lW9lqsI+HQViJj7KbrFZNsg3rN6vwtfJsEPJctdvC26Dl8+A8vJWTQwPkiMJJSqliakR2P3XPuRRvHc28Q1tqytuVEJAJvF2/yGnGWauFLtI1D1yWlfMCNHnWftFUA3pXwr3DQoc7agKiBQjS+LU+Z58gGYB7o="
  file:
    - 'xmoto-0.6.0.deb'
    - 'xmoto-0.6.0.rpm'
    - 'xmoto-0.6.0.dmg'
  skip_cleanup: true
  on:
    branch: "release"
    tags: true

